# Generated by Django 4.2.6 on 2023-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_alter_admin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(default='images/admin.png', upload_to='admins'),
        ),
    ]
